# Generated by Django 4.2.1 on 2024-05-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age',
            field=models.IntegerField(),
        ),
    ]
