# Generated by Django 4.2.1 on 2024-05-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_database', '0005_rename_name_customer_given_name_customer_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(max_length=80, verbose_name='Druh pojisteni')),
                ('insurance_amount', models.IntegerField(verbose_name='Pojistna castka')),
            ],
        ),
    ]
