# Generated by Django 4.2.1 on 2024-05-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_database', '0006_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='insurance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance_database.insurance', verbose_name='Druh pojisteni'),
        ),
    ]
