# Generated by Django 4.2.1 on 2024-05-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_database', '0009_insurance_alter_customer_insurance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='insurance_type',
        ),
    ]
